### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by perone** [ahkarami/Deep-Learning-in-Production#1]
Nice list of resources, thanks for putting this together.
I made a [short article](http://blog.christianperone.com/2018/10/pytorch-1-0-tracing-jit-and-libtorch-c-api-to-integrate-pytorch-into-nodejs/) on how to integrate PyTorch on Node.js using the released LibTorch C++ API if you are interested in adding into the list.

**Comment by ahkarami** [comment]
Dear @perone,
Sorry for late response. Thank you very much for your fantastic article. I will add it to the list.
Best

**Comment by perone** [comment]
No problem @ahkarami, thanks for adding it.
