### ISSUE TITLE
How to deploy an image caption pytorch model to flask?

### ISSUE THREAD

**Issue by ghost** [ahkarami/Deep-Learning-in-Production#2]
So I have this existing trained model (image caption) and I want it to deploy in flask. 
I can't find any tutorial on deploying an existing pytorch model to flask.

**Comment by ahkarami** [comment]
Dear @codevinz,
You can use this [tutorial](https://www.pyimagesearch.com/2018/02/05/deep-learning-production-keras-redis-flask-apache/). Using Flask for deploying deep learning models has a general and same structure (I mean that there isn't any different from Keras or PyTorch).
